plugins {
    id 'com.gradleup.shadow' version '9.2.2'
    id 'org.jetbrains.kotlin.jvm' version '2.2.20'
    id 'java'
}

jar {
    manifest.attributes(
            'Main-Class': 'com.sidpatchy.eclaire.Main',
            'Multi-Release': 'true'
    )
}

group = "com.sidpatchy"
version = "1.3.1"

kotlin {
    jvmToolchain(25)
}

repositories {
    mavenCentral()
    maven {
        url = 'https://m2.dv8tion.net/releases'
    }
    maven {
        url = uri("https://maven.pkg.github.com/Sidpatchy/Robin")
        credentials {
            username = project.findProperty("gpr.user") ?: System.getenv("USERNAME")
            password = project.findProperty("gpr.key") ?: System.getenv("TOKEN")
        }
    }
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.14.4'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.14.4'

    implementation 'com.sidpatchy:robin:2.2.7'
    implementation 'net.dv8tion:JDA:6.4.2'

    implementation 'org.apache.logging.log4j:log4j-api:2.26.0'
    implementation 'org.apache.logging.log4j:log4j-core:2.26.0'
    implementation 'org.apache.logging.log4j:log4j-slf4j2-impl:2.26.0'

    implementation 'tools.jackson.dataformat:jackson-dataformat-xml:3.2.0'
    implementation 'tools.jackson.dataformat:jackson-dataformat-yaml:3.2.0'
    implementation 'tools.jackson.dataformat:jackson-dataformat-smile:3.2.0'

    implementation 'org.knowm.xchart:xchart:4.0.2'
}

tasks.test {
    useJUnitPlatform()
}
